"""add_tenant_id_and_soft_delete_to_core_tables

Revision ID: 7e03a46c453f
Revises: cfd129a30f7c
Create Date: 2026-03-04 00:08:11.863498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e03a46c453f'
down_revision: Union[str, Sequence[str], None] = 'cfd129a30f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('inventory', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inventory_tenant_id'), 'inventory', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'inventory', 'tenants', ['tenant_id'], ['id'])
    op.add_column('products', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    op.add_column('shipments', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('shipments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('shipments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'shipments', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.add_column('vehicles', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('vehicles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'tenants', ['tenant_id'], ['id'])
    op.add_column('warehouses', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('warehouses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_warehouses_tenant_id'), 'warehouses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'warehouses', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_index(op.f('ix_warehouses_tenant_id'), table_name='warehouses')
    op.drop_column('warehouses', 'deleted_at')
    op.drop_column('warehouses', 'is_deleted')
    op.drop_column('warehouses', 'tenant_id')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_column('vehicles', 'deleted_at')
    op.drop_column('vehicles', 'is_deleted')
    op.drop_column('vehicles', 'tenant_id')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_column('shipments', 'deleted_at')
    op.drop_column('shipments', 'is_deleted')
    op.drop_column('shipments', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_tenant_id'), table_name='inventory')
    op.drop_column('inventory', 'deleted_at')
    op.drop_column('inventory', 'is_deleted')
    op.drop_column('inventory', 'tenant_id')
    # ### end Alembic commands ###
